In [42]:
import numpy as np

In [43]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [44]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
print(x[2][2])
#Here the first index 
# is for the row 
# and the second for the column

9


In [46]:
x.ndim
# number of dimensions


2

In [47]:
x.size
# number of elements

9

In [48]:
x.shape
#tuple that shows num of elemnets on
# each 

(3, 3)

In [49]:
# we can add, remove & sort an array
# np.append()-for adding elements
# np.delete()-for removing at index
# np.sort()-for sorting "

In [50]:
print(np.append(x,20),'\n')
print(np.delete(x,4),'\n')
print(np.sort(x))

[ 1  2  3  4  5  6  7  8  9 20] 

[1 2 3 4 6 7 8 9] 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
# we can also use np.arange()
# to create a range of element
import numpy as np
x = np.arange(1,30,2)
x.size

15

In [52]:
# we can reshape an array (either)
# 2-dimension or 1-dimension
x.reshape(3,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29]])

In [53]:
# indexing and slicing
x = np.arange(1,10)
print(x[1:4])
print(x[:5])

[2 3 4]
[1 2 3 4 5]


In [54]:
# conditions 
print(x[x>4])
print(x[(x<6)  & (x>4)])




[5 6 7 8 9]
[5]


In [55]:
# operations
# use the sum() function to add all
# elements in an array
# also we can multiply all elements
# at once
print(x.sum())
print(x.min())
print(x.max())
print(x-1)


45
1
9
[0 1 2 3 4 5 6 7 8]


In [56]:
# STATISTICS
# we can use the numpy mean(), median(),
# varience and standard deviation
print(np.mean(x))
print(np.median(x))
print(np.var(x))
print(np.std(x))

5.0
5.0
6.666666666666667
2.581988897471611
